"""New table rows IN

Revision ID: 600911d1114a
Revises: 57366b74f992
Create Date: 2025-01-11 13:37:37.016127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600911d1114a'
down_revision = '57366b74f992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])

    op.create_table('prescription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), nullable=False),
    sa.Column('diagnosis', sa.VARCHAR(length=200), nullable=False),
    sa.Column('medicines', sa.TEXT(), nullable=False),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
